//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDO
    {
        public int id { get; set; }
        public int id_cuenta { get; set; }
        public Nullable<int> saldo1 { get; set; }
        public Nullable<int> nuevo_saldo { get; set; }
    
        public virtual CUENTAS CUENTAS { get; set; }
    }
}
