//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBankC.WSBank {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ROL", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Model")]
    [System.SerializableAttribute()]
    public partial class ROL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.USUARIOS[] USUARIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rol1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.USUARIOS[] USUARIOS {
            get {
                return this.USUARIOSField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOSField, value) != true)) {
                    this.USUARIOSField = value;
                    this.RaisePropertyChanged("USUARIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol1 {
            get {
                return this.rol1Field;
            }
            set {
                if ((object.ReferenceEquals(this.rol1Field, value) != true)) {
                    this.rol1Field = value;
                    this.RaisePropertyChanged("rol1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIOS", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Model")]
    [System.SerializableAttribute()]
    public partial class USUARIOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.CUENTAS[] CUENTASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.ROL ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.USUARIO[] USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.CUENTAS[] CUENTAS {
            get {
                return this.CUENTASField;
            }
            set {
                if ((object.ReferenceEquals(this.CUENTASField, value) != true)) {
                    this.CUENTASField = value;
                    this.RaisePropertyChanged("CUENTAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.ROL ROL {
            get {
                return this.ROLField;
            }
            set {
                if ((object.ReferenceEquals(this.ROLField, value) != true)) {
                    this.ROLField = value;
                    this.RaisePropertyChanged("ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.USUARIO[] USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_rol {
            get {
                return this.id_rolField;
            }
            set {
                if ((this.id_rolField.Equals(value) != true)) {
                    this.id_rolField = value;
                    this.RaisePropertyChanged("id_rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.identificacionField, value) != true)) {
                    this.identificacionField = value;
                    this.RaisePropertyChanged("identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CUENTAS", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Model")]
    [System.SerializableAttribute()]
    public partial class CUENTAS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.SALDO[] SALDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.USUARIOS USUARIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool state_acField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.SALDO[] SALDO {
            get {
                return this.SALDOField;
            }
            set {
                if ((object.ReferenceEquals(this.SALDOField, value) != true)) {
                    this.SALDOField = value;
                    this.RaisePropertyChanged("SALDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.USUARIOS USUARIOS {
            get {
                return this.USUARIOSField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOSField, value) != true)) {
                    this.USUARIOSField = value;
                    this.RaisePropertyChanged("USUARIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool state_ac {
            get {
                return this.state_acField;
            }
            set {
                if ((this.state_acField.Equals(value) != true)) {
                    this.state_acField = value;
                    this.RaisePropertyChanged("state_ac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Model")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.USUARIOS USUARIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.USUARIOS USUARIOS {
            get {
                return this.USUARIOSField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOSField, value) != true)) {
                    this.USUARIOSField = value;
                    this.RaisePropertyChanged("USUARIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_nameField, value) != true)) {
                    this.user_nameField = value;
                    this.RaisePropertyChanged("user_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SALDO", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Model")]
    [System.SerializableAttribute()]
    public partial class SALDO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppBankC.WSBank.CUENTAS CUENTASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nuevo_saldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal saldo1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppBankC.WSBank.CUENTAS CUENTAS {
            get {
                return this.CUENTASField;
            }
            set {
                if ((object.ReferenceEquals(this.CUENTASField, value) != true)) {
                    this.CUENTASField = value;
                    this.RaisePropertyChanged("CUENTAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_cuenta {
            get {
                return this.id_cuentaField;
            }
            set {
                if ((this.id_cuentaField.Equals(value) != true)) {
                    this.id_cuentaField = value;
                    this.RaisePropertyChanged("id_cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nuevo_saldo {
            get {
                return this.nuevo_saldoField;
            }
            set {
                if ((this.nuevo_saldoField.Equals(value) != true)) {
                    this.nuevo_saldoField = value;
                    this.RaisePropertyChanged("nuevo_saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal saldo1 {
            get {
                return this.saldo1Field;
            }
            set {
                if ((this.saldo1Field.Equals(value) != true)) {
                    this.saldo1Field = value;
                    this.RaisePropertyChanged("saldo1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSBank.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRolbyId", ReplyAction="http://tempuri.org/IService1/GetRolbyIdResponse")]
        AppBankC.WSBank.ROL[] GetRolbyId(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetRolbyId", ReplyAction="http://tempuri.org/IService1/GetRolbyIdResponse")]
        System.IAsyncResult BeginGetRolbyId(int id, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.ROL[] EndGetRolbyId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountbyId", ReplyAction="http://tempuri.org/IService1/GetAccountbyIdResponse")]
        AppBankC.WSBank.CUENTAS[] GetAccountbyId(string id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAccountbyId", ReplyAction="http://tempuri.org/IService1/GetAccountbyIdResponse")]
        System.IAsyncResult BeginGetAccountbyId(string id, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.CUENTAS[] EndGetAccountbyId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetAccount", ReplyAction="http://tempuri.org/IService1/SetAccountResponse")]
        int SetAccount(AppBankC.WSBank.CUENTAS cuenta);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SetAccount", ReplyAction="http://tempuri.org/IService1/SetAccountResponse")]
        System.IAsyncResult BeginSetAccount(AppBankC.WSBank.CUENTAS cuenta, System.AsyncCallback callback, object asyncState);
        
        int EndSetAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetUsuario", ReplyAction="http://tempuri.org/IService1/SetUsuarioResponse")]
        int SetUsuario(AppBankC.WSBank.USUARIOS cuenta);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SetUsuario", ReplyAction="http://tempuri.org/IService1/SetUsuarioResponse")]
        System.IAsyncResult BeginSetUsuario(AppBankC.WSBank.USUARIOS cuenta, System.AsyncCallback callback, object asyncState);
        
        int EndSetUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UptAccount", ReplyAction="http://tempuri.org/IService1/UptAccountResponse")]
        AppBankC.WSBank.Result UptAccount(string idAccount, string numCuenta);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UptAccount", ReplyAction="http://tempuri.org/IService1/UptAccountResponse")]
        System.IAsyncResult BeginUptAccount(string idAccount, string numCuenta, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.Result EndUptAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelAccount", ReplyAction="http://tempuri.org/IService1/DelAccountResponse")]
        AppBankC.WSBank.Result DelAccount(string idAccount);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DelAccount", ReplyAction="http://tempuri.org/IService1/DelAccountResponse")]
        System.IAsyncResult BeginDelAccount(string idAccount, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.Result EndDelAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAmount", ReplyAction="http://tempuri.org/IService1/AddAmountResponse")]
        AppBankC.WSBank.Result AddAmount(string idAccount, double valor);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddAmount", ReplyAction="http://tempuri.org/IService1/AddAmountResponse")]
        System.IAsyncResult BeginAddAmount(string idAccount, double valor, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.Result EndAddAmount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveAmount", ReplyAction="http://tempuri.org/IService1/RemoveAmountResponse")]
        AppBankC.WSBank.Result RemoveAmount(string idAccount, double valor);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/RemoveAmount", ReplyAction="http://tempuri.org/IService1/RemoveAmountResponse")]
        System.IAsyncResult BeginRemoveAmount(string idAccount, double valor, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.Result EndRemoveAmount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSateAccountbyId", ReplyAction="http://tempuri.org/IService1/GetSateAccountbyIdResponse")]
        AppBankC.WSBank.CUENTAS[] GetSateAccountbyId(string idAccount);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSateAccountbyId", ReplyAction="http://tempuri.org/IService1/GetSateAccountbyIdResponse")]
        System.IAsyncResult BeginGetSateAccountbyId(string idAccount, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.CUENTAS[] EndGetSateAccountbyId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        AppBankC.WSBank.SALDO[] GetBalance(string idAccount);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        System.IAsyncResult BeginGetBalance(string idAccount, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.SALDO[] EndGetBalance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByUserAndPass", ReplyAction="http://tempuri.org/IService1/GetUserByUserAndPassResponse")]
        AppBankC.WSBank.USUARIO[] GetUserByUserAndPass(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUserByUserAndPass", ReplyAction="http://tempuri.org/IService1/GetUserByUserAndPassResponse")]
        System.IAsyncResult BeginGetUserByUserAndPass(string user, string pass, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.USUARIO[] EndGetUserByUserAndPass(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRolByIdUser", ReplyAction="http://tempuri.org/IService1/GetRolByIdUserResponse")]
        AppBankC.WSBank.USUARIOS[] GetRolByIdUser(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetRolByIdUser", ReplyAction="http://tempuri.org/IService1/GetRolByIdUserResponse")]
        System.IAsyncResult BeginGetRolByIdUser(int idUser, System.AsyncCallback callback, object asyncState);
        
        AppBankC.WSBank.USUARIOS[] EndGetRolByIdUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AppBankC.WSBank.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRolbyIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRolbyIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.ROL[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.ROL[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAccountbyIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAccountbyIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.CUENTAS[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.CUENTAS[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UptAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UptAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.Result Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.Result)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DelAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DelAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.Result Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.Result)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.Result Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.Result)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoveAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemoveAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.Result Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.Result)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSateAccountbyIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSateAccountbyIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.CUENTAS[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.CUENTAS[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.SALDO[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.SALDO[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserByUserAndPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserByUserAndPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.USUARIO[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.USUARIO[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRolByIdUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRolByIdUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppBankC.WSBank.USUARIOS[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppBankC.WSBank.USUARIOS[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AppBankC.WSBank.IService1>, AppBankC.WSBank.IService1 {
        
        private BeginOperationDelegate onBeginGetRolbyIdDelegate;
        
        private EndOperationDelegate onEndGetRolbyIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetRolbyIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAccountbyIdDelegate;
        
        private EndOperationDelegate onEndGetAccountbyIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetAccountbyIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetAccountDelegate;
        
        private EndOperationDelegate onEndSetAccountDelegate;
        
        private System.Threading.SendOrPostCallback onSetAccountCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetUsuarioDelegate;
        
        private EndOperationDelegate onEndSetUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onSetUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginUptAccountDelegate;
        
        private EndOperationDelegate onEndUptAccountDelegate;
        
        private System.Threading.SendOrPostCallback onUptAccountCompletedDelegate;
        
        private BeginOperationDelegate onBeginDelAccountDelegate;
        
        private EndOperationDelegate onEndDelAccountDelegate;
        
        private System.Threading.SendOrPostCallback onDelAccountCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddAmountDelegate;
        
        private EndOperationDelegate onEndAddAmountDelegate;
        
        private System.Threading.SendOrPostCallback onAddAmountCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveAmountDelegate;
        
        private EndOperationDelegate onEndRemoveAmountDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveAmountCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSateAccountbyIdDelegate;
        
        private EndOperationDelegate onEndGetSateAccountbyIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetSateAccountbyIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBalanceDelegate;
        
        private EndOperationDelegate onEndGetBalanceDelegate;
        
        private System.Threading.SendOrPostCallback onGetBalanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserByUserAndPassDelegate;
        
        private EndOperationDelegate onEndGetUserByUserAndPassDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserByUserAndPassCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRolByIdUserDelegate;
        
        private EndOperationDelegate onEndGetRolByIdUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetRolByIdUserCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetRolbyIdCompletedEventArgs> GetRolbyIdCompleted;
        
        public event System.EventHandler<GetAccountbyIdCompletedEventArgs> GetAccountbyIdCompleted;
        
        public event System.EventHandler<SetAccountCompletedEventArgs> SetAccountCompleted;
        
        public event System.EventHandler<SetUsuarioCompletedEventArgs> SetUsuarioCompleted;
        
        public event System.EventHandler<UptAccountCompletedEventArgs> UptAccountCompleted;
        
        public event System.EventHandler<DelAccountCompletedEventArgs> DelAccountCompleted;
        
        public event System.EventHandler<AddAmountCompletedEventArgs> AddAmountCompleted;
        
        public event System.EventHandler<RemoveAmountCompletedEventArgs> RemoveAmountCompleted;
        
        public event System.EventHandler<GetSateAccountbyIdCompletedEventArgs> GetSateAccountbyIdCompleted;
        
        public event System.EventHandler<GetBalanceCompletedEventArgs> GetBalanceCompleted;
        
        public event System.EventHandler<GetUserByUserAndPassCompletedEventArgs> GetUserByUserAndPassCompleted;
        
        public event System.EventHandler<GetRolByIdUserCompletedEventArgs> GetRolByIdUserCompleted;
        
        public AppBankC.WSBank.ROL[] GetRolbyId(int id) {
            return base.Channel.GetRolbyId(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRolbyId(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRolbyId(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.ROL[] EndGetRolbyId(System.IAsyncResult result) {
            return base.Channel.EndGetRolbyId(result);
        }
        
        private System.IAsyncResult OnBeginGetRolbyId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BeginGetRolbyId(id, callback, asyncState);
        }
        
        private object[] OnEndGetRolbyId(System.IAsyncResult result) {
            AppBankC.WSBank.ROL[] retVal = this.EndGetRolbyId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRolbyIdCompleted(object state) {
            if ((this.GetRolbyIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRolbyIdCompleted(this, new GetRolbyIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRolbyIdAsync(int id) {
            this.GetRolbyIdAsync(id, null);
        }
        
        public void GetRolbyIdAsync(int id, object userState) {
            if ((this.onBeginGetRolbyIdDelegate == null)) {
                this.onBeginGetRolbyIdDelegate = new BeginOperationDelegate(this.OnBeginGetRolbyId);
            }
            if ((this.onEndGetRolbyIdDelegate == null)) {
                this.onEndGetRolbyIdDelegate = new EndOperationDelegate(this.OnEndGetRolbyId);
            }
            if ((this.onGetRolbyIdCompletedDelegate == null)) {
                this.onGetRolbyIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRolbyIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetRolbyIdDelegate, new object[] {
                        id}, this.onEndGetRolbyIdDelegate, this.onGetRolbyIdCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.CUENTAS[] GetAccountbyId(string id) {
            return base.Channel.GetAccountbyId(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAccountbyId(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAccountbyId(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.CUENTAS[] EndGetAccountbyId(System.IAsyncResult result) {
            return base.Channel.EndGetAccountbyId(result);
        }
        
        private System.IAsyncResult OnBeginGetAccountbyId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return this.BeginGetAccountbyId(id, callback, asyncState);
        }
        
        private object[] OnEndGetAccountbyId(System.IAsyncResult result) {
            AppBankC.WSBank.CUENTAS[] retVal = this.EndGetAccountbyId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAccountbyIdCompleted(object state) {
            if ((this.GetAccountbyIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAccountbyIdCompleted(this, new GetAccountbyIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAccountbyIdAsync(string id) {
            this.GetAccountbyIdAsync(id, null);
        }
        
        public void GetAccountbyIdAsync(string id, object userState) {
            if ((this.onBeginGetAccountbyIdDelegate == null)) {
                this.onBeginGetAccountbyIdDelegate = new BeginOperationDelegate(this.OnBeginGetAccountbyId);
            }
            if ((this.onEndGetAccountbyIdDelegate == null)) {
                this.onEndGetAccountbyIdDelegate = new EndOperationDelegate(this.OnEndGetAccountbyId);
            }
            if ((this.onGetAccountbyIdCompletedDelegate == null)) {
                this.onGetAccountbyIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAccountbyIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetAccountbyIdDelegate, new object[] {
                        id}, this.onEndGetAccountbyIdDelegate, this.onGetAccountbyIdCompletedDelegate, userState);
        }
        
        public int SetAccount(AppBankC.WSBank.CUENTAS cuenta) {
            return base.Channel.SetAccount(cuenta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSetAccount(AppBankC.WSBank.CUENTAS cuenta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetAccount(cuenta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSetAccount(System.IAsyncResult result) {
            return base.Channel.EndSetAccount(result);
        }
        
        private System.IAsyncResult OnBeginSetAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppBankC.WSBank.CUENTAS cuenta = ((AppBankC.WSBank.CUENTAS)(inValues[0]));
            return this.BeginSetAccount(cuenta, callback, asyncState);
        }
        
        private object[] OnEndSetAccount(System.IAsyncResult result) {
            int retVal = this.EndSetAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetAccountCompleted(object state) {
            if ((this.SetAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetAccountCompleted(this, new SetAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetAccountAsync(AppBankC.WSBank.CUENTAS cuenta) {
            this.SetAccountAsync(cuenta, null);
        }
        
        public void SetAccountAsync(AppBankC.WSBank.CUENTAS cuenta, object userState) {
            if ((this.onBeginSetAccountDelegate == null)) {
                this.onBeginSetAccountDelegate = new BeginOperationDelegate(this.OnBeginSetAccount);
            }
            if ((this.onEndSetAccountDelegate == null)) {
                this.onEndSetAccountDelegate = new EndOperationDelegate(this.OnEndSetAccount);
            }
            if ((this.onSetAccountCompletedDelegate == null)) {
                this.onSetAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetAccountCompleted);
            }
            base.InvokeAsync(this.onBeginSetAccountDelegate, new object[] {
                        cuenta}, this.onEndSetAccountDelegate, this.onSetAccountCompletedDelegate, userState);
        }
        
        public int SetUsuario(AppBankC.WSBank.USUARIOS cuenta) {
            return base.Channel.SetUsuario(cuenta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSetUsuario(AppBankC.WSBank.USUARIOS cuenta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetUsuario(cuenta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSetUsuario(System.IAsyncResult result) {
            return base.Channel.EndSetUsuario(result);
        }
        
        private System.IAsyncResult OnBeginSetUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppBankC.WSBank.USUARIOS cuenta = ((AppBankC.WSBank.USUARIOS)(inValues[0]));
            return this.BeginSetUsuario(cuenta, callback, asyncState);
        }
        
        private object[] OnEndSetUsuario(System.IAsyncResult result) {
            int retVal = this.EndSetUsuario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetUsuarioCompleted(object state) {
            if ((this.SetUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetUsuarioCompleted(this, new SetUsuarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetUsuarioAsync(AppBankC.WSBank.USUARIOS cuenta) {
            this.SetUsuarioAsync(cuenta, null);
        }
        
        public void SetUsuarioAsync(AppBankC.WSBank.USUARIOS cuenta, object userState) {
            if ((this.onBeginSetUsuarioDelegate == null)) {
                this.onBeginSetUsuarioDelegate = new BeginOperationDelegate(this.OnBeginSetUsuario);
            }
            if ((this.onEndSetUsuarioDelegate == null)) {
                this.onEndSetUsuarioDelegate = new EndOperationDelegate(this.OnEndSetUsuario);
            }
            if ((this.onSetUsuarioCompletedDelegate == null)) {
                this.onSetUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginSetUsuarioDelegate, new object[] {
                        cuenta}, this.onEndSetUsuarioDelegate, this.onSetUsuarioCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.Result UptAccount(string idAccount, string numCuenta) {
            return base.Channel.UptAccount(idAccount, numCuenta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUptAccount(string idAccount, string numCuenta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUptAccount(idAccount, numCuenta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.Result EndUptAccount(System.IAsyncResult result) {
            return base.Channel.EndUptAccount(result);
        }
        
        private System.IAsyncResult OnBeginUptAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idAccount = ((string)(inValues[0]));
            string numCuenta = ((string)(inValues[1]));
            return this.BeginUptAccount(idAccount, numCuenta, callback, asyncState);
        }
        
        private object[] OnEndUptAccount(System.IAsyncResult result) {
            AppBankC.WSBank.Result retVal = this.EndUptAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUptAccountCompleted(object state) {
            if ((this.UptAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UptAccountCompleted(this, new UptAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UptAccountAsync(string idAccount, string numCuenta) {
            this.UptAccountAsync(idAccount, numCuenta, null);
        }
        
        public void UptAccountAsync(string idAccount, string numCuenta, object userState) {
            if ((this.onBeginUptAccountDelegate == null)) {
                this.onBeginUptAccountDelegate = new BeginOperationDelegate(this.OnBeginUptAccount);
            }
            if ((this.onEndUptAccountDelegate == null)) {
                this.onEndUptAccountDelegate = new EndOperationDelegate(this.OnEndUptAccount);
            }
            if ((this.onUptAccountCompletedDelegate == null)) {
                this.onUptAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUptAccountCompleted);
            }
            base.InvokeAsync(this.onBeginUptAccountDelegate, new object[] {
                        idAccount,
                        numCuenta}, this.onEndUptAccountDelegate, this.onUptAccountCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.Result DelAccount(string idAccount) {
            return base.Channel.DelAccount(idAccount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDelAccount(string idAccount, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelAccount(idAccount, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.Result EndDelAccount(System.IAsyncResult result) {
            return base.Channel.EndDelAccount(result);
        }
        
        private System.IAsyncResult OnBeginDelAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idAccount = ((string)(inValues[0]));
            return this.BeginDelAccount(idAccount, callback, asyncState);
        }
        
        private object[] OnEndDelAccount(System.IAsyncResult result) {
            AppBankC.WSBank.Result retVal = this.EndDelAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDelAccountCompleted(object state) {
            if ((this.DelAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DelAccountCompleted(this, new DelAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DelAccountAsync(string idAccount) {
            this.DelAccountAsync(idAccount, null);
        }
        
        public void DelAccountAsync(string idAccount, object userState) {
            if ((this.onBeginDelAccountDelegate == null)) {
                this.onBeginDelAccountDelegate = new BeginOperationDelegate(this.OnBeginDelAccount);
            }
            if ((this.onEndDelAccountDelegate == null)) {
                this.onEndDelAccountDelegate = new EndOperationDelegate(this.OnEndDelAccount);
            }
            if ((this.onDelAccountCompletedDelegate == null)) {
                this.onDelAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDelAccountCompleted);
            }
            base.InvokeAsync(this.onBeginDelAccountDelegate, new object[] {
                        idAccount}, this.onEndDelAccountDelegate, this.onDelAccountCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.Result AddAmount(string idAccount, double valor) {
            return base.Channel.AddAmount(idAccount, valor);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddAmount(string idAccount, double valor, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddAmount(idAccount, valor, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.Result EndAddAmount(System.IAsyncResult result) {
            return base.Channel.EndAddAmount(result);
        }
        
        private System.IAsyncResult OnBeginAddAmount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idAccount = ((string)(inValues[0]));
            double valor = ((double)(inValues[1]));
            return this.BeginAddAmount(idAccount, valor, callback, asyncState);
        }
        
        private object[] OnEndAddAmount(System.IAsyncResult result) {
            AppBankC.WSBank.Result retVal = this.EndAddAmount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddAmountCompleted(object state) {
            if ((this.AddAmountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddAmountCompleted(this, new AddAmountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddAmountAsync(string idAccount, double valor) {
            this.AddAmountAsync(idAccount, valor, null);
        }
        
        public void AddAmountAsync(string idAccount, double valor, object userState) {
            if ((this.onBeginAddAmountDelegate == null)) {
                this.onBeginAddAmountDelegate = new BeginOperationDelegate(this.OnBeginAddAmount);
            }
            if ((this.onEndAddAmountDelegate == null)) {
                this.onEndAddAmountDelegate = new EndOperationDelegate(this.OnEndAddAmount);
            }
            if ((this.onAddAmountCompletedDelegate == null)) {
                this.onAddAmountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddAmountCompleted);
            }
            base.InvokeAsync(this.onBeginAddAmountDelegate, new object[] {
                        idAccount,
                        valor}, this.onEndAddAmountDelegate, this.onAddAmountCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.Result RemoveAmount(string idAccount, double valor) {
            return base.Channel.RemoveAmount(idAccount, valor);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRemoveAmount(string idAccount, double valor, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemoveAmount(idAccount, valor, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.Result EndRemoveAmount(System.IAsyncResult result) {
            return base.Channel.EndRemoveAmount(result);
        }
        
        private System.IAsyncResult OnBeginRemoveAmount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idAccount = ((string)(inValues[0]));
            double valor = ((double)(inValues[1]));
            return this.BeginRemoveAmount(idAccount, valor, callback, asyncState);
        }
        
        private object[] OnEndRemoveAmount(System.IAsyncResult result) {
            AppBankC.WSBank.Result retVal = this.EndRemoveAmount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemoveAmountCompleted(object state) {
            if ((this.RemoveAmountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveAmountCompleted(this, new RemoveAmountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveAmountAsync(string idAccount, double valor) {
            this.RemoveAmountAsync(idAccount, valor, null);
        }
        
        public void RemoveAmountAsync(string idAccount, double valor, object userState) {
            if ((this.onBeginRemoveAmountDelegate == null)) {
                this.onBeginRemoveAmountDelegate = new BeginOperationDelegate(this.OnBeginRemoveAmount);
            }
            if ((this.onEndRemoveAmountDelegate == null)) {
                this.onEndRemoveAmountDelegate = new EndOperationDelegate(this.OnEndRemoveAmount);
            }
            if ((this.onRemoveAmountCompletedDelegate == null)) {
                this.onRemoveAmountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveAmountCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveAmountDelegate, new object[] {
                        idAccount,
                        valor}, this.onEndRemoveAmountDelegate, this.onRemoveAmountCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.CUENTAS[] GetSateAccountbyId(string idAccount) {
            return base.Channel.GetSateAccountbyId(idAccount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSateAccountbyId(string idAccount, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSateAccountbyId(idAccount, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.CUENTAS[] EndGetSateAccountbyId(System.IAsyncResult result) {
            return base.Channel.EndGetSateAccountbyId(result);
        }
        
        private System.IAsyncResult OnBeginGetSateAccountbyId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idAccount = ((string)(inValues[0]));
            return this.BeginGetSateAccountbyId(idAccount, callback, asyncState);
        }
        
        private object[] OnEndGetSateAccountbyId(System.IAsyncResult result) {
            AppBankC.WSBank.CUENTAS[] retVal = this.EndGetSateAccountbyId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSateAccountbyIdCompleted(object state) {
            if ((this.GetSateAccountbyIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSateAccountbyIdCompleted(this, new GetSateAccountbyIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSateAccountbyIdAsync(string idAccount) {
            this.GetSateAccountbyIdAsync(idAccount, null);
        }
        
        public void GetSateAccountbyIdAsync(string idAccount, object userState) {
            if ((this.onBeginGetSateAccountbyIdDelegate == null)) {
                this.onBeginGetSateAccountbyIdDelegate = new BeginOperationDelegate(this.OnBeginGetSateAccountbyId);
            }
            if ((this.onEndGetSateAccountbyIdDelegate == null)) {
                this.onEndGetSateAccountbyIdDelegate = new EndOperationDelegate(this.OnEndGetSateAccountbyId);
            }
            if ((this.onGetSateAccountbyIdCompletedDelegate == null)) {
                this.onGetSateAccountbyIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSateAccountbyIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetSateAccountbyIdDelegate, new object[] {
                        idAccount}, this.onEndGetSateAccountbyIdDelegate, this.onGetSateAccountbyIdCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.SALDO[] GetBalance(string idAccount) {
            return base.Channel.GetBalance(idAccount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetBalance(string idAccount, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBalance(idAccount, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.SALDO[] EndGetBalance(System.IAsyncResult result) {
            return base.Channel.EndGetBalance(result);
        }
        
        private System.IAsyncResult OnBeginGetBalance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idAccount = ((string)(inValues[0]));
            return this.BeginGetBalance(idAccount, callback, asyncState);
        }
        
        private object[] OnEndGetBalance(System.IAsyncResult result) {
            AppBankC.WSBank.SALDO[] retVal = this.EndGetBalance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBalanceCompleted(object state) {
            if ((this.GetBalanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBalanceCompleted(this, new GetBalanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBalanceAsync(string idAccount) {
            this.GetBalanceAsync(idAccount, null);
        }
        
        public void GetBalanceAsync(string idAccount, object userState) {
            if ((this.onBeginGetBalanceDelegate == null)) {
                this.onBeginGetBalanceDelegate = new BeginOperationDelegate(this.OnBeginGetBalance);
            }
            if ((this.onEndGetBalanceDelegate == null)) {
                this.onEndGetBalanceDelegate = new EndOperationDelegate(this.OnEndGetBalance);
            }
            if ((this.onGetBalanceCompletedDelegate == null)) {
                this.onGetBalanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBalanceCompleted);
            }
            base.InvokeAsync(this.onBeginGetBalanceDelegate, new object[] {
                        idAccount}, this.onEndGetBalanceDelegate, this.onGetBalanceCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.USUARIO[] GetUserByUserAndPass(string user, string pass) {
            return base.Channel.GetUserByUserAndPass(user, pass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUserByUserAndPass(string user, string pass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserByUserAndPass(user, pass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.USUARIO[] EndGetUserByUserAndPass(System.IAsyncResult result) {
            return base.Channel.EndGetUserByUserAndPass(result);
        }
        
        private System.IAsyncResult OnBeginGetUserByUserAndPass(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            string pass = ((string)(inValues[1]));
            return this.BeginGetUserByUserAndPass(user, pass, callback, asyncState);
        }
        
        private object[] OnEndGetUserByUserAndPass(System.IAsyncResult result) {
            AppBankC.WSBank.USUARIO[] retVal = this.EndGetUserByUserAndPass(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserByUserAndPassCompleted(object state) {
            if ((this.GetUserByUserAndPassCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserByUserAndPassCompleted(this, new GetUserByUserAndPassCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserByUserAndPassAsync(string user, string pass) {
            this.GetUserByUserAndPassAsync(user, pass, null);
        }
        
        public void GetUserByUserAndPassAsync(string user, string pass, object userState) {
            if ((this.onBeginGetUserByUserAndPassDelegate == null)) {
                this.onBeginGetUserByUserAndPassDelegate = new BeginOperationDelegate(this.OnBeginGetUserByUserAndPass);
            }
            if ((this.onEndGetUserByUserAndPassDelegate == null)) {
                this.onEndGetUserByUserAndPassDelegate = new EndOperationDelegate(this.OnEndGetUserByUserAndPass);
            }
            if ((this.onGetUserByUserAndPassCompletedDelegate == null)) {
                this.onGetUserByUserAndPassCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserByUserAndPassCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserByUserAndPassDelegate, new object[] {
                        user,
                        pass}, this.onEndGetUserByUserAndPassDelegate, this.onGetUserByUserAndPassCompletedDelegate, userState);
        }
        
        public AppBankC.WSBank.USUARIOS[] GetRolByIdUser(int idUser) {
            return base.Channel.GetRolByIdUser(idUser);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRolByIdUser(int idUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRolByIdUser(idUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppBankC.WSBank.USUARIOS[] EndGetRolByIdUser(System.IAsyncResult result) {
            return base.Channel.EndGetRolByIdUser(result);
        }
        
        private System.IAsyncResult OnBeginGetRolByIdUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idUser = ((int)(inValues[0]));
            return this.BeginGetRolByIdUser(idUser, callback, asyncState);
        }
        
        private object[] OnEndGetRolByIdUser(System.IAsyncResult result) {
            AppBankC.WSBank.USUARIOS[] retVal = this.EndGetRolByIdUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRolByIdUserCompleted(object state) {
            if ((this.GetRolByIdUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRolByIdUserCompleted(this, new GetRolByIdUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRolByIdUserAsync(int idUser) {
            this.GetRolByIdUserAsync(idUser, null);
        }
        
        public void GetRolByIdUserAsync(int idUser, object userState) {
            if ((this.onBeginGetRolByIdUserDelegate == null)) {
                this.onBeginGetRolByIdUserDelegate = new BeginOperationDelegate(this.OnBeginGetRolByIdUser);
            }
            if ((this.onEndGetRolByIdUserDelegate == null)) {
                this.onEndGetRolByIdUserDelegate = new EndOperationDelegate(this.OnEndGetRolByIdUser);
            }
            if ((this.onGetRolByIdUserCompletedDelegate == null)) {
                this.onGetRolByIdUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRolByIdUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetRolByIdUserDelegate, new object[] {
                        idUser}, this.onEndGetRolByIdUserDelegate, this.onGetRolByIdUserCompletedDelegate, userState);
        }
    }
}
